### ISSUE TITLE
Feature request: keep row.names of the SummarizedExperiment and the iSEEde dataframes in sync

### ISSUE THREAD

**Issue by tomsing1** [iSEE/iSEEde#19] opened 2023-02-02 22:58 UTC
The `embedResults()` method aligns the feature identifiers of the result object with those of the parental SummarizedExperiment.
But when the row.names of the `SummarizedExperiment` are changed afterward, e.g. with `scuttle::uniquifyFeatureNames()` to create user-friendly gene identifiers, the iSEEde DataFrames in the `rowData` slot don't seem to pick up that change. Perhaps that should be enabled?

**Comment by kevinrue** [comment] 2023-03-18 09:29
Thanks for reporting.

Here's my minimum reproducible example (please include one if you can in future issues).

```r
library("iSEEde")
library("airway")
library("DESeq2")
library("iSEE")

# Example data ----

data("airway")
airway$dex <- relevel(airway$dex, "untrt")

dds <- DESeqDataSet(airway, ~ 0 + dex + cell)

dds <- DESeq(dds)
res_deseq2 <- results(dds, contrast = list("dextrt", "dexuntrt"))
head(res_deseq2)

# iSEE ---

airway <- embedContrastResults(res_deseq2, airway, name = "dex: trt vs untrt")
rowData(airway)

app <- iSEE(airway, initial = list(
    DETable(ContrastName="dex: trt vs untrt", HiddenColumns = c("baseMean", 
                                                                "lfcSE", "stat"), PanelWidth = 4L),
    VolcanoPlot(ContrastName="dex: trt vs untrt", PanelWidth = 4L),
    MAPlot(ContrastName="dex: trt vs untrt", PanelWidth = 4L)
))

# if (interactive()) {
#     shiny::runApp(app)
# }

# Issue 19 ----

library(scuttle)
library(org.Hs.eg.db)
rowData(airway)
rowData(airway)[["iSEEde"]]
rowData(airway)[["iSEEde"]][["dex: trt vs untrt"]]
rowData(airway)[["ENSEMBL"]] <- rownames(airway)
rowData(airway)[["SYMBOL"]] <- mapIds(org.Hs.eg.db, rownames(airway), "SYMBOL", "ENSEMBL")
# The next line introduces the issue
rownames(airway) <- uniquifyFeatureNames(rowData(airway)[["ENSEMBL"]], rowData(airway)[["SYMBOL"]])
airway
rowData(airway)
```

To be honest, it feels more like a bug in `SummarizedExperiment` or `S4Vectors` than in `iSEE` itself.
The `rownames` replacement method for `SummarizedExperiment`, outsources the job to base R `dimnames`, which ultimately passes the ball back to the replacement method for `dimnames` in `SummarizedExperiment` here
https://github.com/Bioconductor/SummarizedExperiment/blob/8df97720354bdeecaf947f574dddd09da02d55b2/R/SummarizedExperiment-class.R#L415

From the looks of it, the method only replaces the slots `NAMES` and `colData`, but does not bother updating the slot `rowRanges`. That seems to be the issue to me, which means the fix should take place in `SummarizedExperiment`, not `iSEE`.

I'll have to discuss it to make sure that's the case.

**Comment by hpages** [comment] 2023-03-25 06:53
I don't think it's realistic to expect in general that the rownames of the parental SummarizedExperiment get propagated to the individual columns of the DataFrame returned by `rowData(se)`. Even though this would maybe sound like a reasonable thing to do for the `iSEEde` column of this DataFrame (i.e. for `rowData(airway)[["iSEEde"]]`), doing this _in general_, i.e. for all columns in `rowData(airway)` and `colData(airway)` (yes, there would be no reason to not do it for `colData(airway)` too) has many implications that should not be taken lightly, as I tried to explain here https://github.com/Bioconductor/SummarizedExperiment/issues/71.

So at this point it seems that we just have to accept the fact that `rowData(airway)[["iSEEde"]]` is special and will require special treatment, not because this column is itself a DataFrame, but because of its importance in the context of **iSEEde**. I'm not familiar with the **iSEEde** package but I guess that `rowData(airway)[["iSEEde"]]` plays a central role here. Is it accurate to say that this column is not a intended for the user but for **iSEEde** internal business?

Concretely the special treatment would consist in defining a getter for this column that takes care of the propagating the rownames of the parental SummarizedExperiment. In the same way that the setter `embedContrastResults()` took care of it. The getter would just do something like this:
```
get_iseede_data <- function(se)
{
    iseede_data <- rowData(se)[["iSEEde"]]
    rownames(iseede_data) <- rownames(se)
    iseede_data
}
```
and would be defined and used in the **iSEEde** package. I don't know if it needs to be exported. Does the user need to access this data or is this **iSEEde** internal business only?

I would also suggest that the setter (`embedContrastResults()`) does not even bother to set rownames on the `rowData(se)[["iSEEde"]]` DataFrame. This will avoid the confusing and error-prone situation where the user accesses this column directly (that is, with `rowData(se)[["iSEEde"]]` and not with `get_iseede_data(se)`), but the rownames they see on it are no longer valid because the rownames of the parent SE have changed. Better not see rownames at all than wrong ones.

So in the end, what I'm suggesting is that the responsibility of setting the rownames on the `iSEEde` column is transferred from the setter to the getter.

Does this make sense?

H.

**Comment by kevinrue** [comment] 2023-03-27 08:41
Must be telepathy... or more likely common sense: the concept of a new dedicated getter clicked in my mind over the week-end.

> yes, there would be no reason to not do it for colData(se) too

It crossed my mind too. I had left it out to focus on rowData in the first place, but admittedly it's essential to consider this as part of the same discussion.

Don't get me wrong Hervé, you've explained it very well here and in the linked issue in SummarizedExperiment.

> Is it accurate to say that this column is not intended for the user but for iSEEde internal business?

Indeed, this feature request caught me by surprise, as I was not expecting users to retrieve information once stored (they can use the original separate table that is not embedded in the SummarizedExperiment object). `iSEEde` stores the nested DataFrame, only for `iSEE` to later access it interactively. 

> I don't know if it needs to be exported. Does the user need to access this data or is this iSEEde's internal business only?

I don't know either. This issue does not give much context about the actual use case. Like I said, I would expect users to work on the original data.frame, not the embedded table.

In terms of `iSEEde`'s internal business, the plan was to use the rownames to match selections of features in assays and rowData. That being said, common sense is back up and running: since rowData is kept in sync with assays, `iSEEde` should use integer indices rather than names.

> I would also suggest that the setter (embedContrastResults()) does not even bother to set rownames on the iSEEde column.

Makes absolute sense, especially given my latest point above.

> So in the end, what I'm suggesting is that the responsibility of setting the rownames on the iSEEde column is transferred from the setter to the getter.

We landed at the same conclusion indeed. Thanks for your time and experience!

**Comment by hpages** [comment] 2023-03-27 16:54
Yup, trans-continental long wave telepathic communications! :wink:

**Comment by hpages** [comment] 2023-03-27 17:35
@kevinrue Have you ever considered using a dot name (`.iSEEde`) for this special column? It's a cosmetic thing only but maybe it manages to send the message to the end user that they are not supposed to mess around with this column.

FWIW at some point in the past I started to play with the idea of formalizing the dotted column concept in order to distinguish between user-oriented columns and reserved/private columns in the DataFrame returned by `mcols()` (the generalization of `rowData()` for any Vector derivative), but only in my head. I didn't go very far with this: too many problems, too complicated, too disruptive. At the time I quickly came to the conclusion that using a dedicated slot and accessor for this would be a much better approach to the public/private columns problem. Note that this is exactly what SingleCellExperiment does with their `int_elementMetadata` and `int_colData` slots and accessors.

BTW I recently offered to move some of the **SingleCellExperiment** goodies to the **SummarizedExperiment** package so that they're available to all SE derivatives (see https://github.com/Bioconductor/BiocClassesWorkingGroup/issues/9#issuecomment-1452716528). However, it seems that maybe we should go one step further by moving the `int_elementMetadata` slot and accessors all the way down to Vector objects. It's a big project, don't know when I'll be able to work on something like this. But I'm less afraid to touch S4 classes internals these days than I was in the past now that we have the [**updateObject** package](https://bioconductor.org/packages/updateObject) to help fix old serialized S4 instances.

**Comment by kevinrue** [comment] 2023-03-28 15:48
Step 1: add a function to list available contrast results in #27

**Comment by kevinrue** [comment] 2023-03-28 16:02
@hpages 

> Have you ever considered using a dot name 

I don't want to perjure myself against the all-encompassing nature of "ever" , but it's very possible that came up during the development of `iSEE`.  If it did, the concept clearly didn't stick.

> send the message to the end user that they are not supposed to mess around with this column

I'm sure I don't need to tell you how much damage the `@` operator is already doing, with users sniffing around dark corners of S4 objects. Call me cynical, but I'm not sure how effective that extra dot would end up being.

> FWIW at some point in the past I started to play with the idea of formalizing the dotted column concept in order to distinguish between user-oriented columns and reserved/private columns 

That I like a lot more (maybe because a formal implementation would mean less work on me downstream).

> BTW I recently offered to move some of the SingleCellExperiment goodies to the SummarizedExperiment package so that they're available to all SE derivatives (see https://github.com/Bioconductor/BiocClassesWorkingGroup/issues/9#issuecomment-1452716528).

That I would like even more. Teaching Bioconductor 3 times a year in my institute, I teach all my students that "SingleCellExperiment" is but a name, and that I use that class for all my analyses including bulk and others, as I care about the _functionality_ of the class more than its name.

> However, it seems that maybe we should go one step further by moving the int_elementMetadata slot and accessor all the way down to Vector objects.

I like where you're going with that and I think that would be great.

> It's a big project, don't know when I'll be able to work on something like this. But I'm less afraid to touch S4 classes internals these days than I was in the past now that we have the [updateObject package](https://bioconductor.org/packages/updateObject) to help fix old serialized S4 instances.

There are so many little bits and pieces that I've wished I could help with over my years using Bioconductor. I'm also more confident sending PR into other people's packages than I was in my early years, but now I'm mostly mindful of choosing my battles without losing myself down every rabbit hole I come across ;)

Any help/feedback/beta-testing you need, let me know!

**Comment by hpages** [comment] 2023-03-28 21:20
Thanks for the feedback. Yep, I've also learned to choose my battles over the years, life is too short! :wink:

**Comment by kevinrue** [comment] 2023-03-29 10:03
Step 2: add a function to extract one or all embedded results in #28

**Comment by kevinrue** [comment] 2023-03-29 14:28
Update MRE:

```r
library("iSEEde")
library("airway")
library("DESeq2")
library("iSEE")

# Example data ----

data("airway")
airway$dex <- relevel(airway$dex, "untrt")

dds <- DESeqDataSet(airway, ~ 0 + dex + cell)

dds <- DESeq(dds)
res_deseq2 <- results(dds, contrast = list("dextrt", "dexuntrt"))
head(res_deseq2)

# iSEE ---

airway <- embedContrastResults(res_deseq2, airway, name = "dex: trt vs untrt")
rowData(airway)

app <- iSEE(airway, initial = list(
    DETable(ContrastName="dex: trt vs untrt", HiddenColumns = c("baseMean", 
                                                                "lfcSE", "stat"), PanelWidth = 4L),
    VolcanoPlot(ContrastName="dex: trt vs untrt", PanelWidth = 4L),
    MAPlot(ContrastName="dex: trt vs untrt", PanelWidth = 4L)
))

# if (interactive()) {
#     shiny::runApp(app)
# }

# Issue 19 ----

library(scuttle)
library(org.Hs.eg.db)
rowData(airway)
# all results
rowData(airway)[["iSEEde"]] # do not do this
contrastResults(airway) # do this instead
# one result
rowData(airway)[["iSEEde"]][["dex: trt vs untrt"]] # do not do this
contrastResults(airway, name = "dex: trt vs untrt") # do this instead

# backup information
rowData(airway)[["ENSEMBL"]] <- rownames(airway)
rowData(airway)[["SYMBOL"]] <- mapIds(org.Hs.eg.db, rownames(airway), "SYMBOL", "ENSEMBL")
# The next line introduces the issue
rownames(airway) <- uniquifyFeatureNames(rowData(airway)[["ENSEMBL"]], rowData(airway)[["SYMBOL"]])
airway
rowData(airway)
# all results
rowData(airway)[["iSEEde"]] # do not do this
contrastResults(airway) # do this instead
# one result
rowData(airway)[["iSEEde"]][["dex: trt vs untrt"]] # do not do this
contrastResults(airway, name = "dex: trt vs untrt") # do this instead
```

Pending bugfix in #31

**Comment by kevinrue** [comment] 2023-03-29 15:22
I think this feature request is now implemented, unit tested, functional in the live app, even giving users access to the new methods and functions. I'll close the issue, but feel free to reopen if anything feels missing or bugged.

**Closed by kevinrue** 2023-03-29 15:22 UTC
